### ISSUE TITLE
How to configure/deploy Job Server with Spark on Mesos?

### ISSUE THREAD

**Issue by seraphliu** [ooyala/spark-jobserver#14]
Hi, 
Thanks for the good work. 

Spark-jobserver is very interesting and I took some time to play with it. However, I can't figure out how to configure/deploy the Job Server when I run Spark on Mesos.  

From the local.conf.template, I can only find the spark.master settings. How can I use mesos.master instead of spark.master?

Could anyone shed some lights on this?

**Comment by sidahmedbenkhaoua** [comment]
Could not resolve hostname hostname1.net: Name or service not known what is the probleme with this error ?

**Comment by velvia** [comment]
Is this still an issue (try with newer versions), or can we close it?
Thanks.

On Wed, Apr 8, 2015 at 10:13 AM, Benkhaoua <notifications@github.com> wrote:

> Could not resolve hostname hostname1.net: Name or service not known what
> is the probleme with this error ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ooyala/spark-jobserver/issues/14#issuecomment-90977860>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by SeraphLiu** [comment]
Please close it. Thanks.

**Comment by linsimiao** [comment]
i met with the same problem, has anyone solved it? Thx in advance.

**Comment by velvia** [comment]
You probably want to visit the spark-jobserver/spark-jobserver site; the ooyala one is not maintained as frequently.

**Comment by linsimiao** [comment]
Thank you.

2018-06-27 14:35 GMT+08:00 Evan Chan <notifications@github.com>:

> You probably want to visit the spark-jobserver/spark-jobserver site; the
> ooyala one is not maintained as frequently.
>
