### ISSUE TITLE
Uncaught error when initializing StreamingContext.

### ISSUE THREAD

**Issue by bamos** [ooyala/spark-jobserver#31]
Hi, I'm new to Spark and would like to use your jobserver with Spark Streaming.
However, I'm running into the following error when trying to create
a SparkStreamingContext from the SparkContext,
causing the job server to crash.

I couldn't find anything in the repo using a StreamingContext,
so is this something I'm doing wrong, or are StreamingContexts not supported?

Thanks,
Brandon.
# Code.

``` Scala
object StreamingJob extends SparkJob {
  def runJob(sc: SparkContext, config: Config): Any = {
    val batchDuration = 60
    val ssc = new StreamingContext(sc, Seconds(batchDuration))
...
```
# Stack trace.

Line 34 is `val ssc...` above.

```
> job-server[ERROR] Uncaught error from thread [JobServer-akka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
job-server[ERROR] java.lang.VerifyError: Bad type on operand stack
job-server[ERROR] Exception Details:
job-server[ERROR]   Location:
job-server[ERROR]     org/apache/spark/streaming/ui/StreamingTab.<init>(Lorg/apache/spark/streaming/StreamingContext;)V @10: invokespecial
job-server[ERROR]   Reason:
job-server[ERROR]     Type 'org/apache/spark/ui/SparkUI' (current frame, stack[1]) is not assignable to 'org/apache/spark/ui/WebUI'
job-server[ERROR]   Current Frame:
job-server[ERROR]     bci: @10
job-server[ERROR]     flags: { flagThisUninit }
job-server[ERROR]     locals: { uninitializedThis, 'org/apache/spark/streaming/StreamingContext' }
job-server[ERROR]     stack: { uninitializedThis, 'org/apache/spark/ui/SparkUI', 'java/lang/String' }
job-server[ERROR]   Bytecode:
job-server[ERROR]     0000000: 2a2b b600 5ab6 005f 1261 b700 642a b800
job-server[ERROR]     0000010: 682a 2bb6 005a b600 5fb5 004a 2a2a b600
job-server[ERROR]     0000020: 6ab6 006e b500 4d2a 2ab6 006a b600 70b5
job-server[ERROR]     0000030: 004f 2abb 0072 592b b700 74b5 0052 2b2a
job-server[ERROR]     0000040: b600 76b6 007a 2abb 007c 592a b700 7fb6
job-server[ERROR]     0000050: 0083 2ab6 006a 2ab6 0087 b1
job-server[ERROR]
job-server[ERROR]   at org.apache.spark.streaming.StreamingContext.<init>(StreamingContext.scala:155)
job-server[ERROR]   at org.apache.spark.streaming.StreamingContext.<init>(StreamingContext.scala:66)
job-server[ERROR]   at my.package.StreamingJob$.runJob(App.scala:34)
job-server[ERROR]   at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:218)
job-server[ERROR]   at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
job-server[ERROR]   at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
job-server[ERROR]   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
job-server[ERROR]   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
job-server[ERROR]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
job-server[ERROR]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
job-server[ERROR]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
job-server[ERROR]   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
job-server ... finished with exit code 255
```

**Comment by skylabreddy** [comment]
I am also facing the issue in spark. That is I have created twitter app and I mapped with key in program . But I need to know the how to build the application and how to get the twitter/sec. Can any one help on this , thanks .

**Comment by velvia** [comment]
Are you looking for help with Spark Streaming in general, or job server?
Note that the Ooyala repo is not actively developed, you want
spark-jobserver/spark-jobserver.

On Thu, Jun 18, 2015 at 3:45 AM, skylabreddy <notifications@github.com>
wrote:

> I am also facing the issue in spark. That is I have created twitter app
> and I mapped with key in program . But I need to know the how to build the
> application and how to get the twitter/sec. Can any one help on this ,
> thanks .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ooyala/spark-jobserver/issues/31#issuecomment-113104829>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by skylabreddy** [comment]
Hi all.

I would like to setup the one of application running on Spark. I am able to
run small application .

I would like to run one of complex application . Could you have any thing
please help to me to run on spark. thanks .

On Fri, Jun 19, 2015 at 10:06 AM, Evan Chan <notifications@github.com>
wrote:

> Are you looking for help with Spark Streaming in general, or job server?
> Note that the Ooyala repo is not actively developed, you want
> spark-jobserver/spark-jobserver.
>
> On Thu, Jun 18, 2015 at 3:45 AM, skylabreddy <notifications@github.com>
> wrote:
>
> > I am also facing the issue in spark. That is I have created twitter app
> > and I mapped with key in program . But I need to know the how to build
> the
> > application and how to get the twitter/sec. Can any one help on this ,
> > thanks .
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ooyala/spark-jobserver/issues/31#issuecomment-113104829
> >
> > .
> >
>
>
>
> --
> If you are free, you need to free somebody else.
> If you have some power, then your job is to empower somebody else.
> --- Toni Morrison
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ooyala/spark-jobserver/issues/31#issuecomment-113364799>
> .
>



-- 
*Regards.*



*SkylabReddyInfrastructure Specialist for Cloud CoE , IBM Cloud India , *
*+91-968-664-4000*

**Comment by skylabreddy** [comment]
Can any one suggest my issue here. thanks.
